# Site settings
title: How I decided to learn about Software Development
header-img: img/home-bg.png
email: cjhhh.ta@gmail.com
copyright_name: cjhhh
description: > # this means to ignore newlines until "baseurl:"
  *The Mysterious Software Developer*
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cjhhh
learn_profile: cjhhh
email_username: cjhhh.ta@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
